-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 12:25:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cleaningdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cleaningdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cleaningdb` DEFAULT CHARACTER SET utf8 ;
USE `cleaningdb` ;

-- -----------------------------------------------------
-- Table `cleaningdb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaningdb`.`roles` (
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaningdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaningdb`.`users` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `roles_role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_users_roles1_idx` (`roles_role_name` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_role_name`)
    REFERENCES `cleaningdb`.`roles` (`role_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaningdb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaningdb`.`client` (
  `client_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `users_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `idclient_UNIQUE` (`client_id` ASC) VISIBLE,
  INDEX `fk_client_users1_idx` (`users_login` ASC) VISIBLE,
  CONSTRAINT `fk_client_users1`
    FOREIGN KEY (`users_login`)
    REFERENCES `cleaningdb`.`users` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaningdb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaningdb`.`staff` (
  `staff_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `users_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `idstaff_UNIQUE` (`staff_id` ASC) VISIBLE,
  INDEX `fk_staff_users1_idx` (`users_login` ASC) VISIBLE,
  CONSTRAINT `fk_staff_users1`
    FOREIGN KEY (`users_login`)
    REFERENCES `cleaningdb`.`users` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaningdb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaningdb`.`orders` (
  `order_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `client_client_id` INT(10) UNSIGNED NOT NULL,
  `staff_staff_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `idorders_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_orders_client1_idx` (`client_client_id` ASC) VISIBLE,
  INDEX `fk_orders_staff1_idx` (`staff_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_client1`
    FOREIGN KEY (`client_client_id`)
    REFERENCES `cleaningdb`.`client` (`client_id`),
  CONSTRAINT `fk_orders_staff1`
    FOREIGN KEY (`staff_staff_id`)
    REFERENCES `cleaningdb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaningdb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaningdb`.`services` (
  `service_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(45) NOT NULL,
  `price_per_item` DECIMAL(10,2) UNSIGNED NOT NULL,
  `order_quantity` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`service_id`),
  UNIQUE INDEX `service_id_UNIQUE` (`service_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cleaningdb`.`services_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cleaningdb`.`services_orders` (
  `services_service_id` INT(10) UNSIGNED NOT NULL,
  `orders_order_id` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_services_orders_services1_idx` (`services_service_id` ASC) VISIBLE,
  INDEX `fk_services_orders_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_services_orders_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `cleaningdb`.`orders` (`order_id`),
  CONSTRAINT `fk_services_orders_services1`
    FOREIGN KEY (`services_service_id`)
    REFERENCES `cleaningdb`.`services` (`service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
